recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: OskarsMacbookPro
    homebrewalt:
        apps:
            - git-extras
            - git-flow
            - htop-osx
            - bash-completion
        cask_apps:
            - adobe-air
            - airmail
            - alfred
            - appcleaner
            - bartender
            - caffeine
            - day-o
            - dash
            - dropbox
            - evernote
            - fantastical
            - google-drive
            - gas-mask
            - java
            - onepassword
            - sizeup
            - sublime-text3
            - skype
            - steam
            - spotify
            - the-unarchiver
            - totalfinder
            - vagrant
            - virtualbox
    nodejs:
        apps:
            - grunt
            - grunt-cli 
